### ISSUE TITLE
remove internal style and script from index.html

### ISSUE THREAD

**Issue by barrycumbie** [carlycopley/devBakerProject#3]
remove this code

```javascript


<script>
  $(document).ready(
    function () {
      console.log("ready!");


      $('#baseRectangleFront').draggable();

      $("#adBox").on('click', function () {

        $("#adBox").animate({ left: '500px' });

      })
    }
  );

  //move adBox when clicked
  $(document)
    .on(
      'click',
      (event) => {
        // alert(event.target.id); 
        let $clicked = $('#' + event.target.id);
        // alert($clicked.position().top);

        console.log(
          event.target.id,
          $('#' + event.target.id)
            .position()
            .left);

      })

  //show the position of adbox 
  document.addEventListener("DOMContentLoaded", function () {
    document.getElementById("adBox").addEventListener("click", getPoint);
  });

  function getPoint() {
    let adBox = document.getElementById("adBox");
    let output = document.getElementById("output");

    if (!adBox) {
      output.innerHTML = "Element not found!";
      return;
    }

    let rect = adBox.getBoundingClientRect();

    output.innerHTML =
      "Screen X: " + rect.left + "px<br>" +
      "Screen Y: " + rect.top + "px";
  }
</script>

</html>

```

remove this code

```css

  
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Tourney:ital,wght@0,100..900;1,100..900&display=swap');

h1 {
      font - family: Tourney;
      font - size: 50px;
      padding - top: 15px;
      margin: auto;
    }

    #banner {
      width: px;
      height: 165px;
      background - color: #607D8B;
      background - image: url('data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100"%3E%3Cg fill-rule="evenodd"%3E%3Cg fill="%239C92AC" fill-opacity="0.4"%3E%3Cpath opacity=".5" d="M96 95h4v1h-4v4h-1v-4h-9v4h-1v-4h-9v4h-1v-4h-9v4h-1v-4h-9v4h-1v-4h-9v4h-1v-4h-9v4h-1v-4h-9v4h-1v-4h-9v4h-1v-4H0v-1h15v-9H0v-1h15v-9H0v-1h15v-9H0v-1h15v-9H0v-1h15v-9H0v-1h15v-9H0v-1h15v-9H0v-1h15v-9H0v-1h15V0h1v15h9V0h1v15h9V0h1v15h9V0h1v15h9V0h1v15h9V0h1v15h9V0h1v15h9V0h1v15h9V0h1v15h4v1h-4v9h4v1h-4v9h4v1h-4v9h4v1h-4v9h4v1h-4v9h4v1h-4v9h4v1h-4v9h4v1h-4v9zm-1 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-9-10h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm9-10v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-9-10h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm9-10v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-9-10h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm9-10v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-9-10h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9z"/%3E%3Cpath d="M6 5V0H5v5H0v1h5v94h1V6h94V5H6z"/%3E%3C/g%3E%3C/g%3E%3C/svg%3E');
      margin: 10px;
    }

    #wireframe {
      font - family: monospace;
      height: 20px;
      width: px;
      background - color: darkGrey;
    }

    #target {
      height: 150px;
      border: dotted black;
    }

    #description, #madeBy, #seals {
      font - family: monospace;
      font - size: 20px;
    }

    #seals {
      transform: rotate(180deg);
    }

    #tennisCourt {
      height: 1200px;
      width: 600px;
      background - color: #336699;
      margin: auto;
      position: relative;
    }

    #alleyLeft {
      font - family: Tourney;
      height: 776px;
      width: 45px;
      background - color: #339966;
      border: solid white;
      position: relative;
      top: -1026px;
      left: 112px;
    }

    #alleyRight {
      font - family: Tourney;
      height: 776px;
      width: 45px;
      background - color: #339966;
      border: solid white;
      position: relative;
      top: -1802px;
      left: 420px;
    }

    #baseRectangleFront {
      font - family: Tourney;
      height: 180px;
      width: 270px;
      background - color: #339966;
      border: solid white;
      position: relative;
      top: 174px;
      left: 155px;
    }

    #adBox {
      font - family: Tourney;
      height: 420px;
      width: 130.5px;
      background - color: #339966;
      border: solid white;
      position: relative;
      top: 172px;
      left: 155px;
    }

    #deuceBox {
      font - family: Tourney;
      height: 420px;
      width: 135px;
      background - color: #339966;
      border: solid white;
      position: relative;
      top: -248px;
      left: 285px;
    }

    #baseRectangleBack {
      font - family: Tourney;
      height: 180px;
      width: 270px;
      background-color: #339966;
      border: solid white;
      position: relative;
      top: -250px;
      left: 155px;
    }
  </style>


```
